version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - JVM_OPTS=-Xmx500m -Xms500m
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  kibana:
    depends_on:
      - elasticsearch  
    image: docker.elastic.co/kibana/kibana:7.4.1
    environment:
      - JVM_OPTS=-Xmx500m -Xms500m
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
